# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fasterrcnn/protos/target_assigner.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fasterrcnn.protos import box_coder_pb2 as fasterrcnn_dot_protos_dot_box__coder__pb2
from fasterrcnn.protos import matcher_pb2 as fasterrcnn_dot_protos_dot_matcher__pb2
from fasterrcnn.protos import region_similarity_calculator_pb2 as fasterrcnn_dot_protos_dot_region__similarity__calculator__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='fasterrcnn/protos/target_assigner.proto',
  package='fasterrcnn.protos',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\'fasterrcnn/protos/target_assigner.proto\x12\x11\x66\x61sterrcnn.protos\x1a!fasterrcnn/protos/box_coder.proto\x1a\x1f\x66\x61sterrcnn/protos/matcher.proto\x1a\x34\x66\x61sterrcnn/protos/region_similarity_calculator.proto\"\xbb\x01\n\x0eTargetAssigner\x12+\n\x07matcher\x18\x01 \x01(\x0b\x32\x1a.fasterrcnn.protos.Matcher\x12L\n\x15similarity_calculator\x18\x02 \x01(\x0b\x32-.fasterrcnn.protos.RegionSimilarityCalculator\x12.\n\tbox_coder\x18\x03 \x01(\x0b\x32\x1b.fasterrcnn.protos.BoxCoder')
  ,
  dependencies=[fasterrcnn_dot_protos_dot_box__coder__pb2.DESCRIPTOR,fasterrcnn_dot_protos_dot_matcher__pb2.DESCRIPTOR,fasterrcnn_dot_protos_dot_region__similarity__calculator__pb2.DESCRIPTOR,])




_TARGETASSIGNER = _descriptor.Descriptor(
  name='TargetAssigner',
  full_name='fasterrcnn.protos.TargetAssigner',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='matcher', full_name='fasterrcnn.protos.TargetAssigner.matcher', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='similarity_calculator', full_name='fasterrcnn.protos.TargetAssigner.similarity_calculator', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='box_coder', full_name='fasterrcnn.protos.TargetAssigner.box_coder', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=372,
)

_TARGETASSIGNER.fields_by_name['matcher'].message_type = fasterrcnn_dot_protos_dot_matcher__pb2._MATCHER
_TARGETASSIGNER.fields_by_name['similarity_calculator'].message_type = fasterrcnn_dot_protos_dot_region__similarity__calculator__pb2._REGIONSIMILARITYCALCULATOR
_TARGETASSIGNER.fields_by_name['box_coder'].message_type = fasterrcnn_dot_protos_dot_box__coder__pb2._BOXCODER
DESCRIPTOR.message_types_by_name['TargetAssigner'] = _TARGETASSIGNER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TargetAssigner = _reflection.GeneratedProtocolMessageType('TargetAssigner', (_message.Message,), dict(
  DESCRIPTOR = _TARGETASSIGNER,
  __module__ = 'fasterrcnn.protos.target_assigner_pb2'
  # @@protoc_insertion_point(class_scope:fasterrcnn.protos.TargetAssigner)
  ))
_sym_db.RegisterMessage(TargetAssigner)


# @@protoc_insertion_point(module_scope)
